"use client";

import { useState } from "react";

const sections = [
  {title:"Keyboard navigation", body:"You can move through links, buttons and controls with Tab and Shift + Tab. Press Enter or Space to activate buttons, and use the visible focus indicator to follow your position. A skip link is available at the beginning of this page."},
  {title:"Reading and visual comfort", body:"Use the controls above to increase text size or switch to higher contrast on this page. Your device or browser may also provide zoom, color and reading preferences. Our layouts are designed to adapt to smaller screens."},
  {title:"Motion and animations", body:"We respect your device's reduced-motion preference. You can also turn on reduced motion for this page using the control above."},
  {title:"Forms and support", body:"We aim to provide meaningful labels, clear instructions and understandable feedback. If a form or payment flow is difficult to use, please contact us so we can help you find an alternative."},
  {title:"Known limitations and feedback", body:"Accessibility is ongoing work. We have not completed an independent accessibility audit or certified this website against a specific WCAG conformance level. Some third-party experiences, including hosted payment pages, may have separate accessibility behavior. Please tell us about any barrier you encounter."},
];

function Logo(){return <span className="ac-logo"><span className="ac-logo-icon" aria-hidden="true"><svg viewBox="0 0 48 48" fill="none"><circle cx="24" cy="24" r="22" fill="currentColor" opacity=".11"/><path d="M24 34.3 13.8 24.2c-5.7-5.7 2.7-14.1 8.4-8.4l1.8 1.8 1.8-1.8c5.7-5.7 14.1 2.7 8.4 8.4L24 34.3Z" fill="currentColor"/><path d="M24 7v5M41 24h-5M12 24H7M36 12l-3.5 3.5M15.5 15.5 12 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg></span><span>Understand<span className="ac-rose">Mylove</span></span></span>}

export default function AccessibilityPage(){
 const [fontSize,setFontSize]=useState<"normal"|"large"|"larger">("normal");
 const [contrast,setContrast]=useState(false);
 const [reducedMotion,setReducedMotion]=useState(false);
 const [expanded,setExpanded]=useState<number|null>(null);
 const [allOpen,setAllOpen]=useState(false);
 const isOpen=(i:number)=>allOpen||expanded===i;
 return <main className={`ac-page ac-font-${fontSize} ${contrast?"ac-high-contrast":""} ${reducedMotion?"ac-reduce-motion":""}`}>
   <a href="#accessibility-content" className="ac-skip">Skip to main content</a>
   <header className="ac-header"><div className="ac-container ac-header-inner"><a href="/" aria-label="UnderstandMylove homepage"><Logo/></a><a className="ac-close" href="/" aria-label="Close accessibility page and return to website" title="Back to website"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round"><path d="M6 6l12 12M18 6 6 18"/></svg></a></div></header>
   <section className="ac-hero" aria-labelledby="ac-title"><div className="ac-container"><span className="ac-pill">♡ EVERYONE DESERVES TO FEEL INCLUDED</span><h1 id="ac-title">A little more access.<br/><em>A lot more connection.</em></h1><p>UnderstandMylove should feel welcoming and comfortable to explore. Here you can adjust this page to suit you and learn how we're working towards a more accessible experience.</p></div></section>
   <div id="accessibility-content" className="ac-container ac-content" tabIndex={-1}>
     <section className="ac-controls" aria-labelledby="ac-control-title"><div className="ac-controls-heading"><span className="ac-eyebrow">MAKE YOURSELF COMFORTABLE</span><h2 id="ac-control-title">A page that <em>works for you.</em></h2><p>Try these settings to make the information on this page easier to read.</p></div>
       <div className="ac-settings">
         <fieldset className="ac-setting"><legend>Text size</legend><p>Choose a comfortable reading size.</p><div className="ac-segments"><button type="button" aria-pressed={fontSize==="normal"} onClick={()=>setFontSize("normal")}>A <small>Default</small></button><button type="button" aria-pressed={fontSize==="large"} onClick={()=>setFontSize("large")}>A+ <small>Large</small></button><button type="button" aria-pressed={fontSize==="larger"} onClick={()=>setFontSize("larger")}>A++ <small>Extra large</small></button></div></fieldset>
         <div className="ac-setting"><h3>Higher contrast</h3><p>Use stronger text and background contrast.</p><button type="button" className="ac-toggle" role="switch" aria-checked={contrast} onClick={()=>setContrast(v=>!v)}><span className="ac-track"><span/></span>{contrast?"On":"Off"}</button></div>
         <div className="ac-setting"><h3>Reduce motion</h3><p>Minimize decorative movement on this page.</p><button type="button" className="ac-toggle" role="switch" aria-checked={reducedMotion} onClick={()=>setReducedMotion(v=>!v)}><span className="ac-track"><span/></span>{reducedMotion?"On":"Off"}</button></div>
       </div><div className="ac-control-bottom"><span aria-live="polite">Your preferences apply to this page only.</span><button type="button" onClick={()=>{setFontSize("normal");setContrast(false);setReducedMotion(false)}}>Reset settings ↺</button></div>
     </section>
     <div className="ac-columns"><section className="ac-intro" aria-labelledby="ac-commitment"><span className="ac-eyebrow">OUR APPROACH</span><h2 id="ac-commitment">Connection should be <em>for everyone.</em></h2><p>We want as many people as possible to enjoy our reflection experience, whatever device or way of navigating they use.</p><div className="ac-intro-note"><span aria-hidden="true">♡</span><div><strong>Accessibility is a journey.</strong><p>We aim to make our experience clearer, easier to navigate and more inclusive. Your feedback helps us identify what needs improvement.</p></div></div><a className="ac-text-link" href="/contact">Share accessibility feedback ↗</a></section>
       <section className="ac-details" aria-labelledby="ac-details-title"><div className="ac-details-head"><div><span className="ac-eyebrow">HELPFUL INFORMATION</span><h2 id="ac-details-title">Explore accessibility <em>details.</em></h2></div><button type="button" onClick={()=>{setAllOpen(v=>!v);setExpanded(null)}}>{allOpen?"Collapse all":"Expand all"}</button></div><div className="ac-accordion">{sections.map((s,i)=><article className="ac-item" key={s.title}><h3><button type="button" id={`ac-trigger-${i}`} aria-expanded={isOpen(i)} aria-controls={`ac-panel-${i}`} onClick={()=>{if(allOpen){setAllOpen(false);setExpanded(i)}else setExpanded(expanded===i?null:i)}}><span>{s.title}</span><span className="ac-plus" aria-hidden="true">{isOpen(i)?"−":"+"}</span></button></h3>{isOpen(i)&&<div className="ac-answer" id={`ac-panel-${i}`} role="region" aria-labelledby={`ac-trigger-${i}`}>{s.body}</div>}</article>)}</div></section></div>
     <section className="ac-feedback" aria-labelledby="ac-feedback-title"><span className="ac-feedback-icon" aria-hidden="true">✉</span><div><span className="ac-eyebrow">WE'RE LISTENING</span><h2 id="ac-feedback-title">Found something difficult to use?</h2><p>Tell us which page or feature caused trouble, what happened and (if you're comfortable sharing) which device or assistive technology you use. Please don't include passwords or payment card details.</p></div><a href="/contact">Contact our team <span aria-hidden="true">→</span></a></section>
   </div>
   <section className="ac-bottom"><div className="ac-container"><span className="ac-eyebrow">HERE FOR EVERY STEP</span><h2>Everyone belongs <em>in the conversation.</em></h2><p>Thank you for helping us make UnderstandMylove a little better.</p><a href="/help">Explore the Help Center <span aria-hidden="true">→</span></a></div></section>

   <style>{`
   .ac-page{--green:#214d45;--deep:#173b35;--rose:#e76f72;--cream:#fffaf4;--mint:#eaf5ef;--line:rgba(33,77,69,.13);--body-scale:1;min-height:100vh;background:var(--cream);color:var(--deep);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;font-size:calc(16px * var(--body-scale))}.ac-font-large{--body-scale:1.125}.ac-font-larger{--body-scale:1.25}.ac-page *{box-sizing:border-box}.ac-page a{text-decoration:none;color:inherit}.ac-page button{font:inherit;cursor:pointer}.ac-page :is(a,button):focus-visible{outline:3px solid #19846a;outline-offset:4px}.ac-container{width:min(1120px,calc(100% - 44px));margin:0 auto}.ac-skip{position:absolute;top:-100px;left:15px;background:white;color:var(--deep);padding:12px;z-index:100}.ac-skip:focus{top:10px}.ac-header{height:76px;background:var(--cream);border-bottom:1px solid var(--line)}.ac-header-inner{height:100%;display:flex;justify-content:space-between;align-items:center}.ac-logo{display:inline-flex;align-items:center;gap:9px;font:700 24px Georgia,"Times New Roman",serif;letter-spacing:-.7px;color:#1b7b66;white-space:nowrap}.ac-logo-icon{width:35px;height:35px;color:var(--rose)}.ac-logo-icon svg{width:100%;height:100%}.ac-rose{color:var(--rose)}.ac-close{width:43px;height:43px;display:grid;place-items:center;border:1px solid #dfe8e3;border-radius:50%;background:white;color:var(--green)!important;transition:background .2s,transform .2s}.ac-close svg{width:15px;height:15px}.ac-close:hover{background:var(--mint);transform:rotate(90deg)}
   .ac-hero{text-align:center;padding:76px 0 91px;background:radial-gradient(circle at 9% 35%,#ffebe5 0,transparent 43%),radial-gradient(circle at 92% 73%,#e8f5ee 0,transparent 42%),linear-gradient(135deg,var(--cream),#f8fbf8)}.ac-pill{display:inline-block;border:1px solid #f7d9d2;background:#fff0ea;border-radius:40px;color:#90534f;font-size:.625em;font-weight:800;letter-spacing:.11em;padding:10px 16px}.ac-page h1,.ac-page h2{font-family:Georgia,"Times New Roman",serif;letter-spacing:-.045em;font-weight:400}.ac-page h1 em,.ac-page h2 em{color:var(--rose);font-weight:400}.ac-page h1{font-size:clamp(2.8em,5.2vw,4.65em);color:var(--green);line-height:1.12;margin:24px 0 18px}.ac-hero p{font-size:.94em;line-height:1.85;color:#657971;max-width:650px;margin:0 auto}.ac-content{padding:70px 0 100px}.ac-eyebrow{font-size:.625em;letter-spacing:.14em;font-weight:850;color:#16806b}.ac-controls{border:1px solid #eadfd8;background:white;border-radius:23px;padding:35px 39px;box-shadow:0 19px 55px rgba(34,60,47,.055)}.ac-controls-heading h2{font-size:clamp(2.1em,4vw,2.8em);color:var(--green);margin:12px 0}.ac-controls-heading p,.ac-setting p{font-size:.8em;color:#6d8177;line-height:1.75}.ac-settings{display:grid;grid-template-columns:1.25fr 1fr 1fr;gap:18px;margin-top:29px}.ac-setting{min-width:0;margin:0;border:1px solid var(--line);border-radius:14px;background:#fcfdfb;padding:19px}.ac-setting legend{font-size:.875em;font-weight:750;padding:0 5px}.ac-setting h3{font-size:.875em;margin:0;font-weight:750}.ac-setting p{margin:9px 0 18px}.ac-segments{display:flex;gap:6px;flex-wrap:wrap}.ac-segments button{border:1px solid #d9e8de;background:white;color:var(--green);border-radius:8px;min-width:65px;flex:1;padding:10px 5px;font-size:.875em;font-weight:800}.ac-segments button small{display:block;font-size:.7em;font-weight:500;margin-top:4px}.ac-segments button[aria-pressed=true]{background:var(--green);color:white;border-color:var(--green)}.ac-toggle{display:flex;align-items:center;gap:11px;background:transparent;border:0;color:var(--green);font-size:.78em;font-weight:700;padding:2px}.ac-track{width:42px;height:24px;border-radius:20px;background:#cbd7d0;display:flex;align-items:center;padding:3px;transition:background .2s}.ac-track span{display:block;width:18px;height:18px;background:white;border-radius:50%;transition:transform .2s}.ac-toggle[aria-checked=true] .ac-track{background:#21866d}.ac-toggle[aria-checked=true] .ac-track span{transform:translateX(18px)}.ac-control-bottom{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:19px;font-size:.68em;color:#82958a}.ac-control-bottom button{border:0;background:none;color:#16806b;font-weight:750;padding:8px}
   .ac-columns{display:grid;grid-template-columns:.83fr 1.17fr;gap:75px;margin-top:90px;align-items:start}.ac-intro h2,.ac-details h2{font-size:clamp(2.15em,4vw,3.15em);color:var(--green);line-height:1.15;margin:14px 0}.ac-intro>p{font-size:.85em;line-height:1.85;color:#687d71}.ac-intro-note{display:flex;gap:15px;background:#fff0ea;border:1px solid #f6ddd3;border-radius:15px;padding:20px;margin:27px 0}.ac-intro-note>span{font-size:1.5em;color:var(--rose)}.ac-intro-note strong{font-size:.85em}.ac-intro-note p{font-size:.73em;line-height:1.75;color:#856b62}.ac-text-link{font-size:.8em;color:#16806b!important;font-weight:750}.ac-text-link:hover{text-decoration:underline}.ac-details-head{display:flex;align-items:end;justify-content:space-between;gap:15px;margin-bottom:20px}.ac-details-head>button{white-space:nowrap;border:0;background:none;color:#16806b;font-size:.75em;font-weight:750;padding:10px}.ac-accordion{background:white;border:1px solid var(--line);border-radius:17px;overflow:hidden}.ac-item+.ac-item{border-top:1px solid var(--line)}.ac-item h3{margin:0}.ac-item h3 button{display:flex;align-items:center;justify-content:space-between;gap:15px;width:100%;text-align:left;background:white;border:0;padding:19px 22px;color:var(--deep);font-size:.85em;font-weight:700}.ac-item h3 button:hover{background:#fafdfb}.ac-plus{flex:0 0 29px;width:29px;height:29px;border-radius:50%;display:grid;place-items:center;background:var(--mint);color:#23876d;font-size:1.35em;font-weight:400}.ac-answer{padding:0 62px 23px 22px;color:#657a6e;font-size:.8em;line-height:1.85}.ac-feedback{display:flex;align-items:center;gap:24px;margin-top:82px;border-radius:19px;padding:30px 33px;background:var(--mint);border:1px solid #d9eadf}.ac-feedback-icon{flex:0 0 48px;width:48px;height:48px;display:grid;place-items:center;background:white;border-radius:14px;color:var(--rose);font-size:1.5em}.ac-feedback>div{flex:1}.ac-feedback h2{font-size:1.7em;color:var(--green);margin:8px 0}.ac-feedback p{font-size:.75em;line-height:1.75;color:#657d70;margin:0}.ac-feedback>a,.ac-bottom a{display:inline-flex;align-items:center;justify-content:center;gap:12px;border-radius:10px;background:var(--rose);color:white!important;padding:15px 19px;font-size:.78em;font-weight:750;white-space:nowrap}.ac-feedback>a:hover,.ac-bottom a:hover{background:#d95e62}
   .ac-bottom{text-align:center;padding:74px 0 82px;background:var(--mint)}.ac-bottom h2{font-size:clamp(2.1em,4.5vw,3.25em);color:var(--green);margin:14px 0}.ac-bottom p{color:#647b70;font-size:.8em;margin-bottom:26px}.ac-footer{background:#173b35;color:white;padding:34px 0}.ac-footer-inner{display:flex;align-items:center;justify-content:space-between;gap:15px}.ac-footer .ac-logo{font-size:1.2em;color:white}.ac-footer .ac-logo-icon{width:28px;height:28px}.ac-footer-inner>span,.ac-footer-inner>a{font-size:.7em;color:#c2d6ce}
   .ac-high-contrast{--green:#092b22;--deep:#09251e;--rose:#a12a35;--cream:#fff;--mint:#e1f1e8;--line:#53685c;color:#09251e}.ac-high-contrast .ac-hero{background:white}.ac-high-contrast :is(.ac-hero p,.ac-setting p,.ac-controls-heading p,.ac-intro>p,.ac-answer,.ac-feedback p,.ac-bottom p){color:#173b35}.ac-high-contrast .ac-eyebrow,.ac-high-contrast .ac-text-link{color:#075c3f}.ac-high-contrast .ac-feedback>a,.ac-high-contrast .ac-bottom a{background:#8e2530}.ac-high-contrast .ac-pill{background:#fff;color:#65212b;border-color:#65212b}.ac-reduce-motion *, .ac-reduce-motion *::before,.ac-reduce-motion *::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}
   @media(max-width:900px){.ac-settings{grid-template-columns:1fr 1fr}.ac-setting:first-child{grid-column:1/-1}.ac-columns{gap:40px}}@media(max-width:720px){.ac-columns{grid-template-columns:1fr;gap:45px;margin-top:67px}.ac-feedback{flex-wrap:wrap}.ac-feedback>a{width:100%}.ac-content{padding:52px 0 75px}}@media(max-width:600px){.ac-container{width:min(100% - 34px,520px)}.ac-header{height:68px}.ac-logo{font-size:20px}.ac-logo-icon{width:30px;height:30px}.ac-close{width:39px;height:39px}.ac-hero{padding:57px 0 65px}.ac-page h1{font-size:clamp(2.5em,9vw,3.45em)}.ac-hero p{font-size:.85em}.ac-controls{padding:24px 18px;border-radius:17px}.ac-settings{grid-template-columns:1fr;gap:11px}.ac-setting:first-child{grid-column:auto}.ac-control-bottom{align-items:flex-start}.ac-details-head{align-items:start}.ac-details h2{font-size:2.2em}.ac-item h3 button{padding:18px 15px}.ac-answer{padding:0 18px 20px 15px}.ac-feedback{padding:23px 19px;gap:13px}.ac-bottom{padding:58px 0 67px}.ac-footer-inner{flex-wrap:wrap}.ac-footer-inner>span{order:3;width:100%}}@media(max-width:360px){.ac-logo{font-size:17px}.ac-controls{padding:20px 14px}.ac-details-head{flex-wrap:wrap}}@media(prefers-reduced-motion:reduce){.ac-page *{transition:none!important;animation:none!important;scroll-behavior:auto!important}}
   `}</style>
 </main>
}
